skill_list = [
    "Select Job",
    "data scientist",
    "web developer",
    "android developer",
    "ios developer",
    "uiux developer",
]

languages = [
    "javascript",
    "python",
    "java",
    "c#",
    "c",
    "c++",
    "php",
    "typescript",
    "swift",
    "go",
    "ruby",
    "kotlin",
    "rust",
    "objective-c",
    "bash",
    "matlab",
    "r",
    "dart",
    "scala",
    "groovy",
    "html/css",
    "sql",
    "assembly",
    "perl",
    "lua",
    "julia",
    "f#",
    "haskell",
    "powershell",
    "visual basic",
]

ds_list = [
    "data visualization",
    "predictive analysis",
    "statistical modeling",
    "data mining",
    "clustering & classification",
    "data analytics",
    "quantitative analysis",
    "web scraping",
    "ml algorithms",
    "keras",
    "pytorch",
    "probability",
    "scikit-learn",
    "tensorflow",
    "flask",
    "streamlit",
    "tensorflow",
    "keras",
    "pytorch",
    "machine learning",
    "deep learning",
    "flask",
    "streamlit",
    "nlp",
    "cnn",
    "rnn",
    "opencv",
    "lstm",
    "knn",
]

web_list = [
    "react",
    "django",
    "node js",
    "react js",
    "php",
    "laravel",
    "magento",
    "wordpress",
    "javascript",
    "angular js",
    "c#",
    "flask",
    "sdk",
    "html",
    "css",
    "github",
    "sql",
    "postman",
]

android_list = [
    "android",
    "android development",
    "flutter",
    "kotlin",
    "xml",
    "java",
    "kivy",
    "git",
    "sdk",
    "sqlite",
]

ios_list = [
    "ios",
    "ios development",
    "swift",
    "cocoa",
    "cocoa touch",
    "xcode",
    "objective-c",
    "sqlite",
    "plist",
    "storekit",
    "ui-kit",
    "av foundation",
    "auto-layout",
]

uiux_list = [
    "ui",
    "user experience",
    "adobe xd",
    "figma",
    "zeplin",
    "balsamiq",
    "prototyping",
    "wireframes",
    "storyframes",
    "adobe photoshop",
    "editing",
    "illustrator",
    "after effects",
    "premier pro",
    "indesign",
    "wireframe",
    "solid",
    "grasp",
    "user research",
]
